name: Daily Stock Alert Bot

on:
  schedule:
    - cron: '45 18 * * *'   # 00:15 IST example
  workflow_dispatch:

jobs:
  run-stock-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Run Stock Agent
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: java -jar target/*.jar
